name: Release

on: [push]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Building release
        run: |
          make build
          echo "::set-env name=FILENAME::$(ls dist)"
        shell: bash
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.FILENAME}}
          path: dist/${{env.FILENAME}}

  MacOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Building release
        run: |
          make build
          echo "::set-env name=FILENAME::$(ls dist)"
        shell: bash
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.FILENAME}}
          path: dist/${{env.FILENAME}}

  Windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Building release
        run: |
          make build
          echo "::set-env name=FILENAME::$(ls dist)"
        shell: bash
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.FILENAME}}
          path: dist/${{env.FILENAME}}
