name: Release

on: [push]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Building release
        id: release
        run: |
          make build
          echo "::set-output name=filename::$(ls dist)"
        shell: bash
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.release.outputs.filename }}
          path: dist/${{ steps.release.outputs.filename }}

  MacOS:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Building release
        id: release
        run: |
          make build
          echo "::set-output name=filename::$(ls dist)"
        shell: bash
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.release.outputs.filename }}
          path: dist/${{ steps.release.outputs.filename }}

  Windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Set up Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Building release
        id: release
        run: |
          make build
          echo "::set-output name=filename::$(ls dist)"
        shell: bash
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.release.outputs.filename }}
          path: dist/${{ steps.release.outputs.filename }}
